package com.stephanstan.pontus.excel

/**
 * Created by Owner on 2/28/2016.
 */
import com.stephanstan.pontus.excel.ExcelHelper
import org.apache.poi.xssf.usermodel.XSSFCell
import org.apache.poi.xssf.usermodel.XSSFRow
import org.apache.poi.xssf.usermodel.XSSFSheet
import org.apache.poi.xssf.usermodel.XSSFWorkbook

/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'Owner' at '1/5/16 11:22 PM' with Gradle 2.10
 *
 * @author Owner, @date 1/5/16 11:22 PM
 */
class ExcelFileLaboratory {
    boolean someLibraryMethod() {
        true
    }

    boolean createXlsxFile(){

        String excelFileName = "Test.xlsx"//name of excel file

        String sheetName = "Sheet1";//name of sheet

        XSSFWorkbook wb = new XSSFWorkbook();
        XSSFSheet sheet = wb.createSheet(sheetName)

        //iterating r number of rows
        for (int r=0;r < 5; r++ )
        {
            XSSFRow row = sheet.createRow(r)

            //iterating c number of columns
            for (int c=0;c < 5; c++ )
            {
                XSSFCell cell = row.createCell(c)

                cell.setCellValue("Cell "+r+" "+c)
            }
        }

        FileOutputStream fileOut = new FileOutputStream(excelFileName)

        //write this workbook to an Outputstream.
        wb.write(fileOut);
        fileOut.flush();
        fileOut.close();

        true
    }
    boolean createXlsxFile_01(){

        String excelFileName = "docs/excel/Test_01.xlsx"//name of excel file

        String sheetName = "Sheet1";//name of sheet

        XSSFWorkbook wb = ExcelHelper.createWorkbook()
        XSSFSheet sheet = wb.createSheet(sheetName)

        //iterating r number of rows
        for (int r=0;r < 5; r++ )
        {
            XSSFRow row = sheet.createRow(r)

            //iterating c number of columns
            for (int c=0;c < 5; c++ )
            {
                XSSFCell cell = row.createCell(c)

                cell.setCellValue("Cell "+r+" "+c)
            }
        }

        FileOutputStream fileOut = new FileOutputStream(excelFileName)

        //write this workbook to an Outputstream.
        wb.write(fileOut);
        fileOut.flush();
        fileOut.close();

        true
    }

    boolean createDojangBlinger_01(){

        String excelFileName = "docs/excel/Dojang_Blinger.xlsx"//name of excel file

        String sheetName = "Dojang";//name of sheet

        XSSFWorkbook wb = ExcelHelper.createWorkbook()
        XSSFSheet sheet = wb.createSheet(sheetName)

        //iterating r number of rows
        for (int r=0;r < 5; r++ )
        {
            XSSFRow row = sheet.createRow(r)

            //iterating c number of columns
            for (int c=0;c < 5; c++ )
            {
                XSSFCell cell = row.createCell(c)

                cell.setCellValue("Cell "+r+" "+c)
            }
        }

        FileOutputStream fileOut = new FileOutputStream(excelFileName)

        //write this workbook to an Outputstream.
        wb.write(fileOut);
        fileOut.flush();
        fileOut.close();

        true
    }

}
